plan_defaults: &plan_defaults
  docker:
    - image: jeremietharaud/cfncli:1.0.7
      environment:
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          AWS_REGION: eu-west-3
  steps:
    - checkout
    - run:
        name: Validate stack
        command: |
          cfncli --stack-file private-dns.yaml --region ${AWS_REGION} --validate
    - run:
        name: Plan stack
        command: |
          cfncli --stack-file private-dns.yaml --name private-dns --var Env=${ENV} --tags Env=${ENV},stack=https://github.com/jeremietharaud/aws-cfn-cli-example --region ${AWS_REGION} --plan

apply_defaults: &apply_defaults
  docker:
    - image: jeremietharaud/cfncli:1.0.7
      environment:
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          AWS_REGION: ${AWS_REGION}
  steps:
    - checkout
    - run:
        name: Deploy stack
        command: |
          cfncli --stack-file private-dns.yaml --name private-dns --var Env=${ENV} --tags Env=${ENV},stack=https://github.com/jeremietharaud/aws-cfn-cli-example --region ${AWS_REGION} --apply
    - run:
        name: List stacks
        command: |
          cfncli --ls

destroy_defaults: &destroy_defaults
  docker:
    - image: jeremietharaud/cfncli:1.0.7
      environment:
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          AWS_REGION: ${AWS_REGION}
  steps:
    - checkout
    - run:
        name: Plan destruction of the stack
        command: |
          cfncli --stack-file private-dns.yaml --name private-dns --region ${AWS_REGION} --destroy
    - run:
        name: Destroy stack
        command: |
          cfncli --stack-file private-dns.yaml --name private-dns --region ${AWS_REGION} --destroy --auto-approve


version: 2.1
jobs:
  plan:
    <<: *plan_defaults
    environment:
      ENV: dev
  apply:
    <<: *apply_defaults
    environment:
      ENV: dev
  destroy:
    <<: *destroy_defaults
    environment:
      ENV: dev

workflows:
  version: 2
  deploy:
    jobs:
      - plan:
          filters:
            branches:
              only: [develop, master]
      - request-confirmation:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: [develop, master]
      - apply:
          filters:
            branches:
              only: [develop, master]
          requires:
            - request-confirmation
      - request-destroy-confirmation:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: [develop, master]
      - destroy:
          filters:
            branches:
              only: [develop, master]
          requires:
            - request-destroy-confirmation